### ISSUE TITLE
Lost Parameter

### ISSUE THREAD

**Issue by andyli0123** [Kent1011/flutter_tappay_sdk#1]
無法 Get Prime by Payment Card，會一直得到 `prime: {"success":false,"status":88003,"message":"Lost Parameter","prime":""}` 的結果。（kTapPayAppId 和 kTapPayAppKey 都有改成自己的了）

**Comment by Kent1011** [comment]
[88003](https://docs.tappaysdk.com/tutorial/zh/error.html#ios-sdk-error-code) 是 TapPay這邊認定遺失參數，代表後台設定沒有完成，如果你是要用Apple Pay，要先確定你有照著TapPay文件上的流程先進行設定才可以

Apple Pay > Getting Started
- [Portal 設定](https://docs.tappaysdk.com/apple-pay/zh/portal.html#portal)
- [Apple Pay 設定](https://docs.tappaysdk.com/apple-pay/zh/portal.html#apple-pay)
